project_id = "glaucon-politeia"

[auth]
enabled = true
enable_signup = false
site_url = "https://402v.com"
additional_redirect_urls = [
  "https://402v.com/auth/callback",
  "https://www.402v.com/auth/callback",
  "https://glaucon-politeia.vercel.app/auth/callback",
  "http://localhost:3000/auth/callback",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600
